version: '3.8'

services:
  simplejira-tasks:
    build:
      context: ./simplejira-tasks
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    networks:
      - jira-network

  simplejira-users:
    build:
      context: ./simplejira-users
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    networks:
      - jira-network

  postgres:
    build: .
    image: postgres
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
    networks:
      - jira-network

networks:
  jira-network:
    driver: bridge
